DELIMITER |
CREATE PROCEDURE inserisciPassaggio (IN idN smallint, IN EmailzN varchar (30), IN partenzaN varchar(30), 
									IN arrivoN varchar (30))
	
    BEGIN
		IF  EXISTS ( SELECT EMAILP
					FROM UTENTE_PREMIUM
					WHERE EMAILP = EmailzN ) 
	    THEN IF EXISTS (SELECT *
					    FROM TRAGITTO, UTENTE_PREMIUM
					     WHERE TRAGITTO.EMAILP = UTENTE_PREMIUM.EMAILP AND idN = TRAGITTO.ID)
					          
                                                                    
		THEN INSERT INTO PASSAGGIO (ID_TAPPA, EMAILP, INDIRIZZO_PARTENZA, INDIRIZZO_ARRIVO) 
							values (idN, EmailzN, partenzaN, arrivoN);
		CALL printf ('INSERIMENTO PREMIUM AVVENUTO');	
        END IF;
        END IF;
        /*INSERIMENTO AZIENDALE **/
        
        IF EXISTS (SELECT EMAILA
					FROM UTENTE_AZIENDALE
					WHERE EMAILA = EmailzN )
        /*CONTROLLO GUIDATORE E PASSEGGERE STESSA AZIENDA**/
        THEN IF EXISTS (SELECT *
					   FROM TRAGITTO, UTENTE_AZIENDALE
					   WHERE TRAGITTO.EMAILA = UTENTE_AZIENDALE.EMAILA AND idN = TRAGITTO.ID
					   AND UTENTE_AZIENDALE.NOMEAZIENDA =  (SELECT NOMEAZIENDA
															FROM UTENTE_AZIENDALE
															WHERE UTENTE_AZIENDALE.EMAILA = EmailzN))
		THEN INSERT INTO PASSAGGIO (ID_TAPPA, EMAILA, INDIRIZZO_PARTENZA, INDIRIZZO_ARRIVO) 
									values (idN, EmailzN, partenzaN, arrivoN);    
					CALL printf ('INSERIMENTO AZINEDALE AVVENUTO');
        END IF;
        END IF;
        /* NON STAMPA MESSAGGI D'OUTPUT AL MOMENTO IN CASO DI INSERIMENTO NON AVVENUTO TUTTAVIA FUNZIONA" **/
	END;
|
DELIMITER ;
