CREATE TABLE PASSAGGIO (

	ID_PASSAGGIO SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ID_TAPPA SMALLINT,
	EMAILP VARCHAR(30),
    EMAILA VARCHAR(30),
    INDIRIZZO_PARTENZA VARCHAR(30) NOT NULL,
	INDIRIZZO_ARRIVO VARCHAR(30) NOT NULL,
    
    FOREIGN KEY (ID_TAPPA) REFERENCES TAPPA(ID_TRAGITTO),
    FOREIGN KEY (EMAILP) REFERENCES UTENTE_PREMIUM(EMAILP),
    FOREIGN KEY (EMAILA) REFERENCES UTENTE_AZIENDALE(EMAILA),

    FOREIGN KEY (INDIRIZZO_PARTENZA) REFERENCES TAPPA(VIA),
    FOREIGN KEY (INDIRIZZO_ARRIVO) REFERENCES TAPPA(VIA)

	) ENGINE=INNODB;
