CREATE VIEW PRENOTAZIONE_CAPIENZA (AUTO, POSTI_DISPONIBILI, IDTRAGITTO ,GUIDATORE, TAPPA_CITTA, TAPPA_VIA) AS 
	SELECT TARGA, CAPIENZA-1, TRAGITTO.ID, UTENTE, TAPPA.CITTA, TAPPA.VIA
	FROM PRENOTAZIONE, VEICOLO, TRAGITTO_PRENOTAZIONE, TRAGITTO, TAPPA 
	WHERE (AUTO=TARGA AND PRENOTAZIONE.ID = ID_PREN AND TRAGITTO.ID = ID_TRAG
          AND ID_TRAGITTO= TRAGITTO.ID);
