CREATE TABLE FOTO (

	IDFOTO SMALLINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL_UTENTE VARCHAR(30) NOT NULL,
    PATHFOTO varchar(100) NOT NULL,

    FOREIGN KEY (EMAIL_UTENTE) REFERENCES UTENTE(EMAIL)
    
    ) ENGINE=INNODB;