CREATE TABLE PRENOTAZIONE (

	ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
    INIZIO DATETIME DEFAULT NOW(),
    FINE DATETIME,
    NOTE VARCHAR(300),
    AUTO VARCHAR(10) NOT NULL,
    UTENTE VARCHAR(30) NOT NULL,
    INDIRIZZO_PARTENZA VARCHAR(30) NOT NULL,
    INDIRIZZO_ARRIVO VARCHAR(30) NOT NULL,
    
    FOREIGN KEY(INDIRIZZO_PARTENZA) REFERENCES SOSTA(INDIRIZZO),
    FOREIGN KEY(INDIRIZZO_ARRIVO) REFERENCES SOSTA(INDIRIZZO),
    FOREIGN KEY(UTENTE) REFERENCES UTENTE(EMAIL),
    FOREIGN KEY(AUTO) REFERENCES VEICOLO(TARGA)
        
    ) ENGINE=INNODB;