CREATE TABLE SEGNALAZIONE (
	
    ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(30),
    SOCIETA VARCHAR(30),
	DATA DATE NOT NULL,
    TITOLO VARCHAR(20) NOT NULL,	
    TESTO VARCHAR(200) NOT NULL,
    AUTO VARCHAR(10) NOT NULL,
    
    FOREIGN KEY (AUTO) REFERENCES VEICOLO(TARGA),
    FOREIGN KEY (EMAIL) REFERENCES UTENTE(EMAIL),
    FOREIGN KEY (SOCIETA) REFERENCES SOCIETA(NOME)
	
    ) ENGINE=INNODB;