CREATE VIEW STORICO_PRENOTAZIONI(ID, INIZIO, FINE, NOTE, AUTO, UTENTE, INDIRIZZO_PARTENZA, INDIRIZZO_ARRIVO) as
		
	SELECT ID, INIZIO, FINE, NOTE, AUTO, UTENTE, INDIRIZZO_PARTENZA, INDIRIZZO_ARRIVO
	FROM PRENOTAZIONE;