CREATE TABLE TAPPA (

	ID_TRAGITTO SMALLINT,
    CITTA VARCHAR(20) NOT NULL,
    VIA VARCHAR(30) NOT NULL,
    LAT FLOAT(10, 6) NOT NULL,
    LNG FLOAT(10, 6) NOT NULL,
    ORARIO_ARRIVO DATETIME NOT NULL,
    
    PRIMARY KEY (ID_TRAGITTO, VIA),
    FOREIGN KEY (ID_TRAGITTO) REFERENCES TRAGITTO(ID)
    
    ) ENGINE=INNODB;