CREATE TABLE TRAGITTO (

	ID SMALLINT PRIMARY KEY AUTO_INCREMENT,	
    EMAILP VARCHAR(30),
    EMAILA VARCHAR(30),
	KM SMALLINT NOT NULL,
    TIPO ENUM ('URBANO', 'EXTRA-URBANO', 'AUTOSTRADALE', 'MISTO'),
    
    FOREIGN KEY (EMAILP) REFERENCES UTENTE_PREMIUM(EMAILP),
    FOREIGN KEY (EMAILA) REFERENCES UTENTE_AZIENDALE(EMAILA)
	
    ) ENGINE=INNODB;