CREATE TABLE UTENTE (

	EMAIL VARCHAR(30) PRIMARY KEY,
    PW VARCHAR(30) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    COGNOME VARCHAR(30) NOT NULL,
    DATANASCITA DATE NOT NULL,
    LUOGO VARCHAR(50)
    
    ) ENGINE=INNODB;