CREATE VIEW VEICOLI_DISPONIBILI(TARGA, MODELLO, CAPIENZA, DESCRIZIONE, FERIALE, FESTIVO, SOCIETA, AREA_SOSTA) as

	SELECT TARGA, MODELLO, CAPIENZA, DESCRIZIONE, FERIALE, FESTIVO, SOCIETA, AREA_SOSTA
    FROM VEICOLO
    WHERE STATO = 'NON IN USO'